config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :orders, only: [:destroy, :index, :show, :update]
    resources :addresses
    resources :items, only: [:new, :index, :create, :edit, :update, :destroy, :show]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:show, :index, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do

    devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: 'homes#top'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :confirm]
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :order_details, only: [:show, :index]
    get 'customers/:id/my_page', to: 'customers#my_page', as: 'mypage'
    #論理的退会のルートが以下
    resources :customers do
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      member do
        patch :withdraw
      end
    end

  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '商品登録に成功しました'
      redirect_to admin_items_path
    else
      flash[:alert] = '商品の登録に失敗しました'
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '更新に成功しました'
      redirect_to admin_item_path(@item.id)
    else
      flas[:alert] = '更新に失敗しました'
      render :edit
    end
  end

    def destroy
      item = Item.find(params[:id])
      if item.destroy
        flash[:notice] = '商品の削除に成功しました'
        redirect_to admin_items_path
      else
        flash[:alert] = '商品の削除に失敗しました'
        render :edit
      end
    end




  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div>
  <h4><span style="background-color: gray;">商品の編集</span></h4><br>

  <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :image, '商品画像' %>
      </div>
      <div class="form-group row col-6">
        <%= f.file_field :image, placeholder: "ファイルを選択" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :name, '商品名' %>
      </div>
      <div class="form-group row col-6">
        <%= f.text_field :name, class: "form-control", placeholder: "商品名" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :introduction, '商品説明' %>
      </div>
      <div class="form-group row col-6">
        <%= f.text_area :introduction, class: "form-control", placeholder: "商品の説明文" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :genre_id, 'ジャンル' %>
      </div>
      <div class="form-group row col-6">
        <%= f.collection_select :genre_id, Genre.all, :id, :name,
          { prompt: '--選択してください' },
          { class: 'form-select  mb-3' } %>
      </div>
    </div>
    <div class="row d-flex mb-4">
      <div class="col-3">
        <%= f.label :price, '税抜価格' %>
      </div>
      <div class="col-5">
        <%= f.text_field :price, class: "form-control", placeholder: "金額" %>
      </div>
      <div class="col-1 pt-1">円</div>
    </div>
    <div class="row d-flex">
      <div class="col-3"><p>販売ステータス</p></div>
      <div class="col-3">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active_true, '販売' %>
      </div>
      <div class="col-3">
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active_false, '販売停止' %>
      </div>
    </div>
    <div class="offset-3 col-4 mt-3">
      <%= f.submit "内容を更新", class: 'btn btn-success btn-block' %>
    </div>
    <% end %>
    <div class="offset-8 col-2">
      <%= link_to '削除', admin_item_path(@item), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="row">
  <h4 class="m-3"><span  style="background-color: gray;">商品一覧</span></h4>
  <div class="offset-10"><%= link_to new_admin_item_path, class: 'btn btn-success' do %>
  <i class="fa-solid fa-plus"></i><% end %></div><br>
  <table class="table table-bordered mt-3">
    <thead>
      <tr>
        <th class="col-1 table-secondary">商品id</th>
        <th class="col-4 table-secondary">商品名</td>
        <th class="col-2 table-secondary">税抜価格</td>
        <th class="col-3 table-secondary">ジャンル</td>
        <th class="col-2 table-secondary">ステータス</td>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <th class="col-1"><%= item.id %></th>
          <td class="col-4"><%= link_to item.name, admin_item_path(item) %></td>
          <td class="col-2"><%= item.price.to_s(:delimited) %></td>
          <td class="col-3"><%= item.genre.name %></td>
          <td class="col-2">
            <% if item.is_active %>
              <p class="text-success"><strog>販売中</strog></p>
            <% else %>
              <p class="text-muted"><strog>販売停止</strog></p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<div>
  <h4><span style="background-color: gray;">商品新規登録</span></h4><br>

  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :image, '商品画像' %>
      </div>
      <div class="form-group row col-6">
        <%= f.file_field :image, placeholder: "ファイルを選択" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :name, '商品名' %>
      </div>
      <div class="form-group row col-6">
        <%= f.text_field :name, class: "form-control", placeholder: "商品名" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :introduction, '商品説明' %>
      </div>
      <div class="form-group row col-6">
        <%= f.text_area :introduction, class: "form-control", placeholder: "商品の説明文" %>
      </div>
    </div>
    <div class="row d-flex">
      <div class="col-3">
        <%= f.label :ganru_id, 'ジャンル' %>
      </div>
      <div class="form-group row col-6">
        <%= f.collection_select :genre_id, Genre.all, :id, :name,
          { prompt: '--選択してください' },
          { class: 'form-select mb-3' } %>
      </div>
    </div>
    <div class="row d-flex mb-4">
      <div class="col-3">
        <%= f.label :price, '税抜価格' %>
      </div>
      <div class="col-5">
        <%= f.text_field :price, class: "form-control", placeholder: "金額" %>
      </div>
      <div class="col-1 pt-1">円</div>
    </div>
    <div class="row d-flex">
      <div class="col-3"><p>販売ステータス</p></div>
      <div class="col-3">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active_true, '販売' %>
      </div>
      <div class="col-3">
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active_false, '販売停止' %>
      </div>
    </div>
    <div class="offset-3 col-4 mt-3">
      <%= f.submit "商品を登録", class: 'btn btn-success btn-block' %>
    </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div>
  <h4 class="m-4"><span style="background-color:gray;">商品詳細</span></h4><br>
  <div class="row">
    <div class="col-6 d-flex">
      <% if @item.image.attached? %>
        <%= image_tag @item.image, class: "img-fluid" %>
      <% else %>
        <%= image_tag 'no_image.jpg', class: "img-fluid" %>
      <% end %>
    </div>
    <div class="col-6 row">
      <div class="col-4">
        <p>商品名</p>
        <p>商品説明</p>
        <p>ジャンル</p>
        <p>税込価格<br>(税抜価格)</p>
        <p>販売ステータス</p>
      </div>
      <div class="col-8">
        <p><%= @item.name %></p>
        <p><%= @item.introduction %></p>
        <p><%= @item.genre.name %></p>
        <p><%= @item.add_tax_price.to_s(:delimited) %> <br>(<%= @item.price.to_s(:delimited) %>) 円</p>
        <p><% if @item.is_active %>
              <p class="text-success"><strog>販売中</strog></p>
           <% else %>
              <p class="text-muted"><strog>販売停止</strog></p>
           <% end %></p>
      </div>
    </div>
  </div>
  <div class="row m-4 d-flex justify-content-center">
    <%= link_to '編集する', edit_admin_item_path, class: 'btn btn-success' %>
  </div>
</div>