config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :orders, only: [:destroy, :index, :show, :update]
    resources :addresses
    resources :items, only: [:new, :index, :create, :edit, :update, :destroy, :show]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:show, :index, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do

    devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: 'homes#top'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :confirm]
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :order_details, only: [:show, :index]
    get 'customers/:id/my_page', to: 'customers#my_page', as: 'mypage'
    #論理的退会のルートが以下
    resources :customers do
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      member do
        patch :withdraw
      end
    end

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def name
    first_name + ' ' + last_name
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: 2..10
  validates :last_name, presence: true, length: 2..10
  validates :first_name_kana, presence: true, length: 2..10
  validates :last_name_kana, presence: true, length: 2..10
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { pay_weit: 0, pay_check: 1, make_now: 2, sendup: 3, finish: 4 }

  validates :customer_id, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :status, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item
  
  enum making_status: { no_make: 0, waiting: 1, makeing: 2, makeup: 3 }

  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "#{@customer.first_name}#{@customer.last_name}の変更が完了しました"
    else
      flash[:alert] = "変更に失敗しました"
    end
    redirect_to admin_customers_path
  end

  private


  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの登録に成功しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:alert] = "ジャンルの登録に失敗しました"
      render :index
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = '更新に成功しました'
      redirect_to admin_genres_path
    else
      flash[:alert] = '更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      flash[:notice] = '削除に成功しました'
      redirect_to admin_genres_path
    end
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '商品登録に成功しました'
      redirect_to admin_items_path
    else
      flash[:alert] = '商品の登録に失敗しました'
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '更新に成功しました'
      redirect_to admin_item_path(@item.id)
    else
      flas[:alert] = '更新に失敗しました'
      render :edit
    end
  end

    def destroy
      item = Item.find(params[:id])
      if item.destroy
        flash[:notice] = '商品の削除に成功しました'
        redirect_to admin_items_path
      else
        flash[:alert] = '商品の削除に失敗しました'
        render :edit
      end
    end




  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  
 
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/car_items_helper.rb
module Admin::CarItemsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_datelis_helper.rb
module Admin::OrderDatelisHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div>
  <div>
    <h4><span style="background-color:gray;"><%= @customer.first_name + @customer.last_name %>さんの会員情報編集</span></h4>
  </div>
  <div>
    <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
      <div class="row d-flex">
        <div class="col-3">
          <p>名前</p>
        </div>
        <div class="form-group row col-4">
          <div>
            <%= f.text_field :first_name, class: "form-control", placeholder: "姓" %>
          </div>
        </div>
        <div class="form-group row col-4">
          <div>
            <%= f.text_field :last_name, class: "form-control", placeholder: "名" %>
          </div>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3">
          <p>フリガナ</p>
        </div>
        <div class="form-group row col-4">
          <div>
            <%= f.text_field :first_name_kana, class: "form-control", placeholder: "セイ" %>
          </div>

        </div>
        <div class="form-group row col-4">
          <div>
            <%= f.text_field :last_name_kana, class: "form-control", placeholder: "メイ" %>
          </div>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3">
          <%= f.label :postal_code,"郵便番号" %>
        </div>
        <div class="form-group row col-6">
          <%= f.text_field :postal_code, class: "form-control", placeholder: "0000000(ハイフン無し)" %>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3">
          <%= f.label :address,"住所" %>
        </div>
        <div class="form-group row col-8">
          <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3">
          <%= f.label :telephone_number,"電話番号" %>
        </div>
        <div class="form-group row col-6">
          <%= f.text_field :telephone_number, class: "form-control", placeholder: "ハイフン無し" %>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3">
          <%= f.label :email,"メールアドレス" %>
        </div>
        <div class="form-group row col-6">
          <%= f.text_field :email, class: "form-control", placeholder: "email" %>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-3"><p>販売ステータス</p></div>
        <div class="col-3">
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active_true, '有効' %>
        </div>
        <div class="col-3">
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active_false, '無効' %>
        </div>
      </div>
      <div class="offset-3 col-4 mt-3">
        <%= f.submit "内容を更新", class: 'btn btn-success btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div>
  <div>
    <h4><span style="background-color: gray;">会員一覧</span></h4>
  </div>
  <table class="table table-hover col-10">
    <thead>
      <tr>
        <th class="col-1">会員ID</th>
        <th class="col-4">氏名</th>
        <th class="col-5">メールアドレス</th>
        <th class="col-2">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.first_name + customer.last_name, admin_customer_path(customer) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active? %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-muted">無効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div>
  <div>
    <h4><span style="background-color:gray;"><%= @customer.first_name + @customer.last_name %>さんの会員情報</span></h4>
  </div>
  <div>
    <div class="row mt-5">
      <div class="col-4">
        <p>会員ID</p>
        <p>氏名</p>
        <p>フリガナ</p>
        <p>郵便番号</p>
        <p>住所</p>
        <p>電話番号</p>
        <p>メールアドレス</p>
        <p>会員ステータス</p>
      </div>
      <div class="col-8">
        <p><%= @customer.id %></p>
        <p><%= @customer.first_name %><%= @customer.last_name %></p>
        <p><%= @customer.first_name_kana %><%= @customer.last_name_kana %></p>
        <p><%= @customer.postal_code %></p>
        <p><%= @customer.address %></p>
        <p><%= @customer.telephone_number %></p>
        <p><%= @customer.email %></p>
        <% if @customer.is_active? %>
          <p class="text-success">有効</p>
        <% else %>
          <p class="text-muted">無効</p>
        <% end %>
      </div>
    </div>
    <div class="row mt-4">
      <div class="offset-1 col-3">
        <%= link_to '編集する', edit_admin_customer_path(@customer), class: 'btn btn-success' %>
      </div>
      <div class="col-4">
        <%= link_to '注文一覧を見る', admin_customers_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>