config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :orders, only: [:destroy, :index, :show, :update]
    resources :addresses
    resources :items, only: [:new, :index, :create, :edit, :update, :destroy, :show]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:show, :index, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do

    devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: 'homes#top'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :confirm]
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :order_details, only: [:show, :index]
    get 'customers/:id/my_page', to: 'customers#my_page', as: 'mypage'
    #論理的退会のルートが以下
    resources :customers do
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      member do
        patch :withdraw
      end
    end

  end
end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの登録に成功しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:alert] = "ジャンルの登録に失敗しました"
      render :index
    end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = '更新に成功しました'
      redirect_to admin_genres_path
    else
      flash[:alert] = '更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      flash[:notice] = '削除に成功しました'
      redirect_to admin_genres_path
    end
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div>
  <h4 class="offset-1"><span  style="background-color: gray;">ジャンル編集</span></h4><br>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
      <ul>
        <% @genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch, local: true do |f| %>
    <div class="col form-group row m-5">
      <div class="col-2 form-group row">
        <%= f.label :name, 'ジャンル名' %>
      </div>
      <div class="col-3 form-group row">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-2 form-group row ml-3">
        <%= f.submit '更新', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div>
  <h4 class="offset-1">ジャンル一覧・追加</h4><br>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
      <ul>
        <% @genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class="col form-group row m-5">
      <div class="col-2 form-group row">
        <%= f.label :name, 'ジャンル名' %>
      </div>
      <div class="col-3 form-group row">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="col-2 form-group row ml-3">
        <%= f.submit '追加', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
  <table class="col-5 table table-hover">
    <thead>
      <tr>
        <th class="pl-4">ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <th><%= genre.name %></th>
          <td><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>