config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do

    resources :orders, only: [:destroy, :index, :show, :update]
    resources :addresses
    resources :items, only: [:new, :index, :create, :edit, :update, :destroy, :show]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:show, :index, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do

    devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: 'homes#top'
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:create, :index, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:new, :create, :confirm]
    post 'orders/confirm', to: 'orders#confirm', as: 'confirm'
    get 'orders/thanks', to: 'orders#thanks', as: 'thanks'
    resources :order_details, only: [:show, :index]
    get 'customers/:id/my_page', to: 'customers#my_page', as: 'mypage'
    #論理的退会のルートが以下
    resources :customers do
      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      member do
        patch :withdraw
      end
    end

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def name
    first_name + ' ' + last_name
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: 2..10
  validates :last_name, presence: true, length: 2..10
  validates :first_name_kana, presence: true, length: 2..10
  validates :last_name_kana, presence: true, length: 2..10
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { pay_weit: 0, pay_check: 1, make_now: 2, sendup: 3, finish: 4 }

  validates :customer_id, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :status, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item
  
  enum making_status: { no_make: 0, waiting: 1, makeing: 2, makeup: 3 }

  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '商品登録に成功しました'
      redirect_to admin_items_path
    else
      flash[:alert] = '商品の登録に失敗しました'
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '更新に成功しました'
      redirect_to admin_item_path(@item.id)
    else
      flas[:alert] = '更新に失敗しました'
      render :edit
    end
  end

    def destroy
      item = Item.find(params[:id])
      if item.destroy
        flash[:notice] = '商品の削除に成功しました'
        redirect_to admin_items_path
      else
        flash[:alert] = '商品の削除に失敗しました'
        render :edit
      end
    end




  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  
 
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/car_items_helper.rb
module Admin::CarItemsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_datelis_helper.rb
module Admin::OrderDatelisHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sample_EC-管理者</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/ab55497b72.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <div class="container">
        <div class="row navber navber-expand-lg navbar-dark bg-dark ">
          <div class="col">
            <div class="navber-brand display-3" style="color: white;">LOG</div>
          </div>
          <% if admin_signed_in? %>
            <div class="nav-item  col-2 p-4">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-info" %>
            </div>
            <div class="nav-item col-2 p-4 text-center">
            <%= link_to 'ジャンル一覧', admin_genres_path, class: "btn btn-info" %>
            </div>
            <div class="nav-item col-2 p-4 text-center">
              <%= link_to '商品一覧', admin_items_path, class: "btn btn-info" %>
            </div>
            <div class="nav-item col-2 p-4 text-center">
              <%= link_to '会員一覧', admin_customers_path, class: "btn btn-info" %>
            </div>
            <div class="nav-item col-2 p-4 text-center">
              <%= link_to '注文一覧', admin_order_details_path, class: "btn btn-info" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sample_EC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/ab55497b72.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <div class="container">
        <div class="row navber navber-expand-lg navbar-dark bg-dark ">
          <div class="col-2">
            <a class="navber-brand display-3" href="/">LOG</a>
          </div>
          <% if customer_signed_in? %>
          <div class="nav-item col-2 p-4 text-center">
            <p class="text-light">ようこそ！<%= current_customer.first_name %>さん</p>
          </div>
          <div class="nav-item col-2 p-4 text-center">
            <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-info" %>
          </div>
          <div class="nav-item col-2 p-4 text-center">
            <%= link_to 'マイページ', mypage_path(current_customer), class: "btn btn-success" %>
          </div>
          <div class="nav-item col-2 p-4 text-center">
            <%= link_to 'カートへ', cart_items_path, class: "btn btn-info" %>
          </div>
          <% else %>
          <div class="nav-item offset-3 col-2 p-4 text-center">
            <%= link_to '新規登録', new_customer_registration_path, class: "btn btn-primary" %>
          </div>
          <div class="nav-item col-2 p-4 text-center">
            <%= link_to 'ログイン', customer_session_path, class: "btn btn-success" %>
          </div>
          <% end %>
          <div class="nav-item col-2 p-4 text-center">
            <%= link_to '商品一覧', items_path, class: "btn btn-info" %>
          </div>
        </div>
      </div>
    </header>
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
  </body>
</html>